name: Contributors

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        id: contributors
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          avatarSize: 42

      - name: Modify htmlTable README.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          message: update contributors[no ci]
          path: README.md
          body: '${{steps.contributors.outputs.htmlList}}'
